In [4]:
import pandas as pd

df = pd.read_csv('student_data (1).csv')
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "Bob"],
    "City": ["New York", "Houston", "Chicago", "Houston", "Chicago"],
    "Score": [85, 92, 78, 90, 88]
}

fd = pd.DataFrame(data)

fd['Name'].unique()
len(fd['Name'].unique())

3

In [14]:
df1 = pd.read_csv('student_data_modified.csv')
df1

,Unnamed: 0,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Makrs,Total Marks,A+ in DS,Passed in DS,First Name
0,0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,258.0,Yes,True,Alif
1,1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,NaN,Yes,True,Fatima
2,2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,261.0,Yes,True,Imran
3,3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,238.0,No,True,Jannatul
4,4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,NaN,No,False,Kamal
5,5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,228.0,No,True,Laila
6,6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN,NaN,Yes,True,Mahmudul
7,7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,247.0,Yes,True,Nadia
8,8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,220.0,No,False,Omar
9,9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,266.0,Yes,True,Priya
10,10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,NaN,No,False,Rahim
11,11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,257.0,Yes,True,Sadia
12,12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,229.0,No,True,Tanvir
13,13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN,NaN,No,False,Urmi
14,14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,256.0,Yes,True,Wahiduzzaman
15,15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN,NaN,Yes,True,Ziaur
16,16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,273.0,Yes,True,Afsana
17,17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,261.0,Yes,True,Babul
18,18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,NaN,NaN,No,False,Faria
19,19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,261.0,Yes,True,Nasir

In [15]:
df1['Data Structure Marks'].unique()
df1['Data Structure Marks'].nunique()

df['Name'].unique()
len(df['Name'].unique())

KeyError: 'Name'

In [ ]:
df1.nunique()
df.isnull()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,True,True,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,True,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,True,True,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False
13,False,False,True,True,True,False,False,False,False
14,False,False,False,False,False,False,False,False,False
15,False,False,False,False,True,False,False,False,False
16,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False
18,False,False,True,True,True,False,False,False,False
19,False,False,False,False,False,False,False,False,False

In [19]:
df1['Data Structure Marks'].isnull()
df1['Data Structure Marks'].notnull()

df1['Python Marks'].hasnans
df1['StudentID'].hasnans

False