In [10]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "Bob"],
    "City": ["New York", "Houston", "Chicago", "Houston", "Chicago"],
    "Score": [85, 92, 78, 90, 88]
}

fd = pd.DataFrame(data)

fd

fd.duplicated().sum()

fd.drop_duplicates()
fd

fd.drop_duplicates(inplace=True)

data

{'Name': ['Alice', 'Bob', 'Charlie', 'Alice', 'Bob'],
 'City': ['New York', 'Houston', 'Chicago', 'Houston', 'Chicago'],
 'Score': [85, 92, 78, 90, 88]}

In [12]:
fd.drop_duplicates(subset=['Name'])

      Name      City  Score
0    Alice  New York     85
1      Bob   Houston     92
2  Charlie   Chicago     78

In [15]:
fd.drop_duplicates(subset=['Name'])

fd.drop_duplicates(subset=['Name'], keep='last')

      Name     City  Score
2  Charlie  Chicago     78
3    Alice  Houston     90
4      Bob  Chicago     88