In [7]:

import pandas as pd

df = pd.read_csv('student_completed_data.csv')
df

group = df.groupby('Instructor')
group.sum()
group.min()
group.max()

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Location,Total Marks
Instructor,,,,,,,
Mr. David,PH0018,Wahiduzzaman,Completed,2024-09-07,2024-12-31,Sylhet,291
Mr. Karim,PH0020,Tariq Hasan,Completed,2024-08-11,2024-11-07,Sylhet,291
Ms. Salma,PH0016,Ziaur Rahman,Completed,2024-09-01,2024-12-23,Rajshahi,300

In [8]:
group.first()

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Location,Total Marks
Instructor,,,,,,,
Mr. David,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Sylhet,254
Mr. Karim,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Dhaka,271
Ms. Salma,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Khulna,300

In [9]:
group.last()

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Location,Total Marks
Instructor,,,,,,,
Mr. David,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Dhaka,278
Mr. Karim,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Khulna,253
Ms. Salma,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Rajshahi,234